apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-generator
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs-generator
  template:
    metadata:
      labels:
        app: logs-generator
    spec:
      containers:
        - name: logs-generator
          image: chentex/random-logger
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/log/nginx
              name: logs-generator
      volumes:
        - name: logs-generator
          emptyDir: {}

