apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-logs
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-logs
  template:
    metadata:
      labels:
        app: nginx-logs
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/log/nginx
              name: nginx-logs
      volumes:
        - name: nginx-logs
          emptyDir: {}
